### ISSUE TITLE
tile.wrap(true)

### ISSUE THREAD

**Issue by mbostock** [d3/d3-tile#10]
Related to http://leafletjs.com/reference.html#tilelayer-nowrap

For Mercator tiles it would be nice to enable wrapping.

**Comment by curran** [comment]
It looks like @jasondavies attempted this in his example [Wrapped d3.geo.tile](http://bl.ocks.org/jasondavies/0051a06829e72b423ba9). The tile provider there is broken, so I made a fork [that uses OSM](http://bl.ocks.org/curran/47a4a010b72aa5b592adf961c43f8f19). It doesn't work properly, but maybe there are some ideas there we can draw from.

**Comment by curran** [comment]
[![image](https://cloud.githubusercontent.com/assets/68416/16356365/5724aa06-3af2-11e6-964a-2ea567fb2d8c.png)](http://bl.ocks.org/curran/47a4a010b72aa5b592adf961c43f8f19)

**Comment by curran** [comment]
So I [tried implementing this in d3-tile](http://bl.ocks.org/curran/2bc8428c875d069cf16e61b4f1b3e0db), but it turns out to be a bit tricky. This is because the tile image transform needs to depend on the original x coordinate, but the tile URL x needs to be wrapped.

Some ideas:

 * Since wrapping only concerns the URL, it could be implemented inside the URL generator.
 * We could add a special property, say `x`, to each tile address array. This could be used for generating the URL, whereas the original `d[0]` x tile coordinate can still be used to drive the transform.

**Comment by curran** [comment]
Maybe the structure returned for each tile could be modified completely, to look something like this:

```js
{
  x: // Tile X for URL (with wrapping applied)
  y: // Tile Y for URL
  z: // Tile Z for URL
  transform: // transform to apply to image (without wrapping applied)
}
```

Having transforms returned per tile like this would obviate the need for `tiles.transform`. It would also make it easier to deal with tiles at different zoom levels at the same time (e.g. for showing a blurry tile in the background until all of its quadtree children load).

**Comment by curran** [comment]
Maybe the structure returned for each tile could be modified completely, to look something like this:

```js
{
  x: // Tile X for URL (with wrapping applied)
  y: // Tile Y for URL
  z: // Tile Z for URL
  transform: // transform to apply to image (without wrapping applied)
}
```

Having transforms returned per tile like this would obviate the need for `tiles.transform`. It would also make it easier to deal with tiles at different zoom levels at the same time (e.g. for showing a blurry tile in the background until all of its quadtree children load).

**Comment by curran** [comment]
I think I nailed the wrapping logic in a [second attempt](http://bl.ocks.org/curran/cb4de7e43890d5a60179762e94804bfb):

![image](https://cloud.githubusercontent.com/assets/68416/16356885/843e02d2-3b04-11e6-8c10-efef0b2dd078.png)

If we unpack the existing logic for the rows and columns ranges, it looks like this:

```js
colMin = Math.max(0, Math.floor((x0 - x) / k)),
colMax = Math.max(0, Math.ceil((x1 - x) / k)),
rowMin = Math.max(0, Math.floor((y0 - y) / k)),
rowMax = Math.max(0, Math.ceil((y1 - y) / k)),
cols = d3Array.range(colMin, colMax),
rows = d3Array.range(rowMin, rowMax);
```

Using `Math.max(0...` on `colMin` is what was preventing Westward wrapping. That was changed to this:

```js
colMin = Math.floor((x0 - x) / k),
```

Using `Math.max(0...` on `colMax` was confusing to me, and I'm not sure what case the `Math.max` is handling here, so I changed it to:

```js
colMax = Math.ceil((x1 - x) / k),
```

Using `Math.max(0...` on `rowMin` has the perfect behavior of excluding tiles beyond the top of the map.

Using `Math.max(0...` on `rowMax` was als confusing to me, and I'm not sure what case the `Math.max` is handling here. The value of `rowMax` going too high was causing the invalid image tiles to be requested, going too far South on the map. Since the maximum row value is part of a quadtree address, the maximum valid value depends on the zoom level, namely 2^z. To account for this, I changed the logic for `rowMax` to this:

```js
rowMax = Math.min(Math.ceil((y1 - y) / k), 1 << z0),
```

Testing this out by zooming in and out at the southern end of the map seems to indicate it is working correctly.

**Comment by curran** [comment]
Here's an [example that shows wrapping being turned on and off](http://bl.ocks.org/curran/d497d9c7611ed7278bbcae91454a906c).

With the addition of a `wrap` boolean, the row and column logic looks like this:

```js
colMin = Math.max(wrap ? -Infinity : 0, Math.floor((x0 - x) / k)),
colMax = Math.min(Math.ceil((x1 - x) / k), wrap ? Infinity : 1 << z0),
rowMin = Math.max(0, Math.floor((y0 - y) / k)),
rowMax = Math.min(Math.ceil((y1 - y) / k), 1 << z0),

cols = d3Array.range(colMin, colMax),
rows = d3Array.range(rowMin, rowMax);
```

**Comment by curran** [comment]
`wrap(true)`
![image](https://cloud.githubusercontent.com/assets/68416/16361957/130fb410-3bbe-11e6-8d8b-f9b77665b767.png)

`wrap(false)`

![image](https://cloud.githubusercontent.com/assets/68416/16361955/f2f4533e-3bbd-11e6-9540-2277eebcda85.png)

**Comment by curran** [comment]
Updating images to be centered:

![image](https://cloud.githubusercontent.com/assets/68416/16513800/0c158872-3f85-11e6-84c6-e481b7e0af5d.png)

![image](https://cloud.githubusercontent.com/assets/68416/16513812/2644b43e-3f85-11e6-83fc-a34a37c852ab.png)

**Comment by davelandry** [comment]
Love love love this feature. Any current plan for an upcoming release?
