### ISSUE TITLE
1.0

### ISSUE THREAD

**Issue by curran** [d3/d3-tile#37]
This library is pretty solid and has not changed much in a year. Perhaps it's time to give it version 1.0.

@mbostock Do you agree?

**Comment by mbostock** [comment]
Personally, I am not happy with the change to represent tiles as objects {x, y, z} rather than arrays [x, y, z], and I also don’t like the redundancy of the additional new tx and ty properties. But it’s possible I haven’t followed the new examples closely enough to understand why these changes were made.

**Comment by Fil** [comment]
From what I understand the change of representation was discussed in https://github.com/d3/d3-tile/issues/15

Now, 6 of the 9 examples use the array, 3 the object:
http://bl.ocks.org/linusmarco/71f80d7c8a53981f5bbfab8167f32a10
http://bl.ocks.org/linusmarco/c75b1d8b0e4996c1eb8a7d9d296636e9
http://bl.ocks.org/curran/96823ad84b0415536980b1cbf57b1dcc

Another issue in the examples is that mapzen resources have disappeared or been renamed to nextzen. Impacts only https://bl.ocks.org/mbostock/5593150 (which could probably be superseded by https://beta.observablehq.com/@mbostock/d3-vector-tiles or similar).

**Comment by mbostock** [comment]
My convention with major version 0 is to increment the minor version (0.0 to 0.1) when making a non-backwards-compatible change. (And starting at major version 1, adopting standard semver rules.) So 0.0.4 should have been released as 0.1.0. But some of the examples were protected from breakage because d3js.org’s d3-tile.v0.js hasn’t been updated to 0.0.4.

**Comment by curran** [comment]
I'm thinking of doing some housekeeping here and releasing the current master as 1.0, then updating all the examples to use it.

Related https://github.com/d3/d3-tile/issues/51

**Comment by curran** [comment]
Here's the plan:

 * Groundwork for updating examples https://github.com/d3/d3-tile/pull/53
 * I'll wait a day or two for any pushback on releasing 1.0, then go ahead with it.

**Comment by mbostock** [comment]
Ref https://github.com/d3/d3-tile/pull/53#issuecomment-513263755.

I’d like to release 1.0 but I think the API needs further work before we do so. I’ll file some issues.

**Comment by mbostock** [comment]
I’ve created a 1.0 milestone: https://github.com/d3/d3-tile/milestone/1

**Comment by mbostock** [comment]
One of the reasons using an array to represent tile coordinates is nice is that *array*.toString produces a unique identifier (key) for each tile, meaning you can use the identity function as the key function with *selection*.data.

```js
[1, 2, 3] + "" // 1,2,3
```
```js
({x: 1, y: 2, z: 3}) + "" // "[object Object]"
```

You can see an example of using this technique here:

https://observablehq.com/@d3/zoomable-map-tiles

Also, you can assign named properties onto arrays, since everything in JavaScript (except for primitives) are objects. So we could for instance use an array [*x*, *y*, *z*] with *tile*.i and *tile*.j as the wrapped (or unwrapped) coordinates. We use this technique on the tiles array itself to expose *tiles*.scale and *tiles*.translate.

That said, it’s awkward to access *tiles*.scale and *tiles*.translate in conjunction with *selection*.data because D3 doesn’t give individual elements access to the array that specified the data. It might be better to expose methods on the tile layout that compute the needed values as-needed, rather than computing them greedily in the returned tile objects.

For instance:

```js
tile.tileX = function([x, y, z]) {
  const Z = Math.max(Math.log(scale) / Math.LN2 - 8, 0);
  return x * (Math.pow(2, Z - z + 8)) + tx - scale / 2;
};
```

(And of course intermediate values such as `Z` could be precomputed, since it only changes when the *tile*.scale changes.)

**Comment by curran** [comment]
Thrilled to see all this renewed activity! I agree that the array form is nicer.

I have no attachment whatsoever to the current API, would be happy to see breaking changes that improve its usability. I think the original reason for it was to do with the case of wrapping, but if that can be solved by adding properties to the array, that sounds good.

**Comment by mbostock** [comment]
We now are missing documentation for:

* *tile*.zoomDelta #9 
* *tile*.clampX
* *tile*.clampY
* *tile*.clamp
* d3.tileWrap

**Comment by mbostock** [comment]
Released!

**Comment by curran** [comment]
Hooray!
